export const youtubePrograms = {
  semesterI: [
    {
      name: "cs50X",
      badge: "cs50x",
      description: "გაიარე CS50X-ის კურსი.",
      url: "/youtubeUniversity/semester-I/cs50x",
      icon: "cs50x",
    },
    {
      name: "cs50P",
      badge: "cs50p",
      description: "გაიარე CS50P-ის კურსი.",
      url: "/youtubeUniversity/semester-I/cs50p",
      icon: "cs50p",
    },
    {
      name: "JavaScript101",
      badge: "js101",
      description: "შეისწავლე JavaScript-ის საფუძვლები.",
      url: "/youtubeUniversity/semester-I/javascript101",
      icon: "javascript",
    },
    {
      name: "C#101",
      badge: "c#101",
      description: "შეისწავლე C#-ის საფუძვლები.",
      url: "/youtubeUniversity/semester-I/c-sharp101",
      icon: "csharp",
    },
    {
      name: "Java101",
      badge: "j101",
      description: "შეისწავლე Java-ს საფუძვლები.",
      url: "/youtubeUniversity/semester-I/java101",
      icon: "java",
    },
    {
      name: "WEB101",
      badge: "web101",
      description: "შეისწავლე Web-ის საფუძვლები.",
      url: "/youtubeUniversity/semester-I/web101",
      icon: "web",
    },
    {
      name: "Tools101",
      badge: "t101",
      description: "შეისწავლე ტექნოლოგიები.",
      url: "/youtubeUniversity/semester-I/t101",
      icon: "t",
    },
  ],
  semesterII: [
    {
      name: "Algorithms",
      badge: "algo",
      description: "ისწავლე ალგორითმები.",
      url: "/youtubeUniversity/semester-II/algorithms",
      icon: "algo",
    },
    {
      name: "TypeScript101",
      badge: "ts101",
      description: "შეისწავლე typescript.",
      url: "/youtubeUniversity/semester-II/typescript",
      icon: "ts",
    },
    {
      name: "Front-End React",
      badge: "fer",
      description: "შეისწავლე React-ი.",
      url: "/youtubeUniversity/semester-II/react",
      icon: "react",
    },
    {
      name: "Front-End Angular",
      badge: "fea",
      description: "შეისწავლე Angular-ი.",
      url: "/youtubeUniversity/semester-II/angular",
      icon: "angular",
    },
    {
      name: "Node WEB",
      badge: "node-web",
      description: "შეისწავლე Node.js.",
      url: "/youtubeUniversity/semester-II/node",
      icon: "nodejs",
    },
    {
      name: "Back-End C#",
      badge: "c#",
      description: "შეისწავლე C#.",
      url: "/youtubeUniversity/semester-II/c-sharp",
      icon: "csharp",
    },
    {
      name: "Back-End Java",
      badge: "j",
      description: "შეისწავლე Java.",
      url: "/youtubeUniversity/semester-II/java",
      icon: "java",
    },
    {
      name: "DB",
      badge: "მონაცემთა ბაზები",
      description: "შეისწავლე მონაცემთა ბაზები.",
      url: "/youtubeUniversity/semester-II/db",
      icon: "db",
    },
  ],
  semesterIII: [
    {
      name: "Next.js",
      badge: "next.js",
      description: "ისწავლე Next.js",
      url: "/youtubeUniversity/semester-III/nextjs",
      icon: "nextjs",
    },
    {
      name: "Django",
      badge: "Django",
      description: "ისწავლე Django",
      url: "/youtubeUniversity/semester-III/django",
      icon: "django",
    },
    {
      name: "DevOps",
      badge: "DevOps",
      description: "ისწავლე DevOps",
      url: "/youtubeUniversity/semester-III/devops",
      icon: "devops",
    },
    {
      name: "BlockChain",
      badge: "BlockChain",
      description: "ისწავლე BlockChain",
      url: "/youtubeUniversity/semester-III/blockchain",
      icon: "blockchain",
    },
    {
      name: "Linux",
      badge: "Linux",
      description: "ისწავლე Linux",
      url: "/youtubeUniversity/semester-III/linux",
      icon: "linux",
    },
    {
      name: "PM",
      badge: "PM",
      description: "ისწავლე პროექტის მენეჯმენტი",
      url: "/youtubeUniversity/semester-III/pm",
      icon: "pm",
    },
  ],
}
